# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/digital_estore
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server
server.port=8080

# Logging
logging.level.root=INFO
logging.level.com.inventrik.digitalestore=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.connectiontimeout=5000

# Sender information
email.from=your-email@gmail.com
email.sender-name=Digital E-Store

# Stripe Configuration
stripe.api.key=your-api-key_starts_with_sk
stripe.webhook.secret=your-webhook-secret

# OAuth2 Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/.well-known/jwks.json

# This will be replaced by the authorization server's issuer URI in production
oauth2.issuer=http://localhost:8080

# Disable auto-configuration of the authorization server
spring.security.oauth2.authorization-server.enabled=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs