CREATE TABLE tenants (
    tenant_id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Tenant ID (auto-increment)',
    shop_name VARCHAR(100) NOT NULL COMMENT 'Store display name',
    shop_email VARCHAR(100) NOT NULL COMMENT 'Store contact email',
    shop_phone VARCHAR(20) COMMENT 'Store contact phone',
    shop_logo VARCHAR(200) COMMENT 'Store logo image URL',
    domain_name VARCHAR(100) COMMENT 'Custom domain name',
    subdomain VARCHAR(50) COMMENT 'Platform subdomain',
    country_region VARCHAR(100) COMMENT 'Store region/country',
    base_currency VARCHAR(20) COMMENT 'Base currency for store',
    multi_currency TINYINT(1) COMMENT 'Multi-currency support: 1=Yes, 0=No',
    tax_id VARCHAR(50) COMMENT 'Tax identification number',
    timezone VARCHAR(50) COMMENT 'Store timezone',
    status VARCHAR(2) NOT NULL DEFAULT '0' COMMENT 'Tenant status: -1=Inactive, 0=Active',
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation timestamp',
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update timestamp',
    PRIMARY KEY (tenant_id),
    UNIQUE KEY uk_shop_email (shop_email),
    UNIQUE KEY uk_subdomain (subdomain),
    UNIQUE KEY uk_domain_name (domain_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Multi-tenant store information';
CREATE TABLE store_themes (
    tenant_id INT UNSIGNED NOT NULL COMMENT 'Tenant ID for multi-tenancy',
    theme_id VARCHAR(32) NOT NULL COMMENT 'Unique theme identifier',
    theme_name VARCHAR(100) COMMENT 'Theme display name',
    tagline VARCHAR(256) COMMENT 'Store tagline',
    description VARCHAR(256) COMMENT 'Theme description',
    banner_image VARCHAR(256) COMMENT 'Banner image URL',
    hero_title VARCHAR(256) COMMENT 'Main hero section title displayed on homepage',
    hero_description TEXT COMMENT 'Hero section description text displayed below title',
    join_cta VARCHAR(256) COMMENT 'Call-to-action text',
    copyright_text VARCHAR(256) COMMENT 'Footer copyright text',
    status VARCHAR(2) NOT NULL DEFAULT '0' COMMENT 'Theme status: -1=Inactive, 0=Active',
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation timestamp',
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update timestamp',
    PRIMARY KEY (tenant_id, theme_id),
    INDEX idx_theme_status (tenant_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Store theme customization';
CREATE TABLE pages (
    tenant_id INT UNSIGNED NOT NULL COMMENT 'Tenant ID for multi-tenancy',
    page_id VARCHAR(32) NOT NULL COMMENT 'Unique page identifier',
    title VARCHAR(255) NOT NULL COMMENT 'Page title',
    slug VARCHAR(100) NOT NULL COMMENT 'URL-friendly page slug',
    content LONGTEXT COMMENT 'Page content',
    meta_title VARCHAR(256) COMMENT 'SEO meta title',
    meta_description VARCHAR(256) COMMENT 'SEO meta description',
    status VARCHAR(20) NOT NULL COMMENT 'Page status',
    visibility VARCHAR(20) NOT NULL COMMENT 'Page visibility setting',
    is_default TINYINT(1) COMMENT 'Is default page: 1=Yes, 0=No',
    language VARCHAR(10) COMMENT 'Page language code',
    template VARCHAR(50) NOT NULL DEFAULT 'default' COMMENT 'Page layout template (default, about, contact, legal, etc.)',
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation timestamp',
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update timestamp',
    published_at TIMESTAMP NULL COMMENT 'Publication timestamp',
    PRIMARY KEY (tenant_id, page_id),
    UNIQUE KEY uk_tenant_slug (tenant_id, slug),
    INDEX idx_page_status (tenant_id, status),
    INDEX idx_page_visibility (tenant_id, visibility)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Custom CMS pages';
CREATE TABLE taxes (
    tenant_id INT UNSIGNED NOT NULL COMMENT 'Tenant ID for multi-tenancy',
    tax_id VARCHAR(32) NOT NULL COMMENT 'Unique tax identifier',
    code VARCHAR(50) NOT NULL COMMENT 'Tax code',
    description VARCHAR(255) COMMENT 'Tax description',
    value DECIMAL(10, 2) NOT NULL COMMENT 'Tax rate or amount',
    default_flag VARCHAR(2) COMMENT 'Is default tax: 1=Yes, 0=No',
    start_date DATE COMMENT 'Tax effective start date',
    end_date DATE COMMENT 'Tax expiration date',
    status VARCHAR(2) NOT NULL DEFAULT '0' COMMENT 'Tax status: -1=Inactive, 0=Active',
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation timestamp',
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update timestamp',
    PRIMARY KEY (tenant_id, tax_id),
    UNIQUE KEY uk_tenant_code (tenant_id, code),
    INDEX idx_tax_status (tenant_id, status),
    INDEX idx_tax_default (tenant_id, default_flag),
    INDEX idx_tax_dates (tenant_id, start_date, end_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tax configuration by region';
